### PR TITLE
Older versions of Visual Studio in documentation

### PR DESCRIPTION
**Pull request by PrashanthSundhar**
Older versions of Visual Studio in documentation as per this ticket request - [Older versions of Visual Studio in documentation](https://support.syncfusion.com/agent/tickets/601219)

### CODE REVIEW

**Comment by PrashanthSundhar** [comment]
rebuild

**Comment by PrashanthSundhar** [comment]
rebuild

**Comment by PrashanthSundhar** [comment]
rebuild

**Comment by PrashanthSundhar** [comment]
Rebuild

**Comment by PrashanthSundhar** [comment]
rebuild

**Comment by PrashanthSundhar** [comment]
rebuild

**Comment by PrashanthSundhar** [comment]
rebuild

**Review by christopherhirudayasamy — APPROVED** [review]

**Comment by PrashanthSundhar** [comment]
rebuild

**Comment by PrashanthSundhar** [comment]
rebuild

**Pull request closed without merging**
